"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.__capnweb_wrap_Api = __capnweb_wrap_Api;
exports.__capnweb_wrap_RpcSession_Api = __capnweb_wrap_RpcSession_Api;
// Generated by capnweb typecheck gen. Do not edit.
const typecheck_1 = require("capnweb/internal/typecheck");
const capnweb_typecheck_1 = require("capnweb-typecheck");
function __capnweb_wrap_Api(stub) {
    return (0, typecheck_1.__capnweb_bindClientValidator)(stub, capnweb_typecheck_1.validators["Api"]);
}
function __capnweb_wrap_RpcSession_Api(session) {
    let main = session.getRemoteMain();
    (0, typecheck_1.__capnweb_bindClientValidator)(main, capnweb_typecheck_1.validators["Api"]);
    return session;
}
