// Generated by capnweb typecheck gen. Do not edit.
import { __capnweb_bindClientValidator } from "capnweb/internal/typecheck";
import { validators } from "capnweb-typecheck";
export function __capnweb_wrap_Api(stub) {
    return __capnweb_bindClientValidator(stub, validators["Api"]);
}
export function __capnweb_wrap_RpcSession_Api(session) {
    let main = session.getRemoteMain();
    __capnweb_bindClientValidator(main, validators["Api"]);
    return session;
}
