// Copyright (c) 2026 Cloudflare, Inc.
// Licensed under the MIT license found in the LICENSE.txt file or at:
//     https://opensource.org/license/mit

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname, extname, join, relative, resolve } from "node:path";
import * as ts from "typescript";
import {
  collectReachableSourceFiles,
  commonDir,
  createProject,
  extractClasses,
} from "./extract.js";
import { emitShadowSources, wrapFunctionName, wrapSessionFunctionName } from "./rewrite.js";
import type { ClassRegistration, ClassSpec, GenOptions, GenResult, TypeSpec } from "./types.js";

export function generate(options: GenOptions): GenResult {
  let prepared = prepare(options);
  let { classes, outAbs, sourceFile, reachableFiles, root } = prepared;

  let entryAbs = emitShadowSources(reachableFiles, sourceFile, outAbs, root, classes.map(c => c.name));
  let importPath = jsImportPath(relative(outAbs, entryAbs));
  let hasDefaultExport = sourceFile.statements.some(statement =>
    (ts.isExportAssignment(statement) && !statement.isExportEquals) ||
    (ts.canHaveModifiers(statement) &&
      ts.getModifiers(statement)?.some(m => m.kind === ts.SyntaxKind.DefaultKeyword)));

  emitArtifacts(prepared);
  writeFileSync(join(outAbs, "worker.entry.ts"),
      emitWorkerEntry(importPath, hasDefaultExport, classes, outAbs, root));
  log(outAbs, "worker.entry.ts");
  return makeGenResult(classes);
}

export function generateValidatorsOnly(options: GenOptions): GenResult {
  let prepared = prepare(options);
  emitArtifacts(prepared);
  return makeGenResult(prepared.classes);
}

type Prepared = {
  classes: ClassSpec[];
  outAbs: string;
  runtimeImport: string;
  sourceFile: ReturnType<typeof createProject>["sourceFile"];
  reachableFiles: ReturnType<typeof collectReachableSourceFiles>;
  root: string;
};

function prepare(options: GenOptions): Prepared {
  let inputAbs = resolve(options.input);
  let outAbs = resolve(options.outDir);
  let runtimeImport = options.runtimeImport ?? "capnweb/internal/typecheck";
  if (!existsSync(inputAbs)) throw new Error(`Input file does not exist: ${options.input}`);

  let project = createProject(inputAbs);
  let sourceFile = project.sourceFile;
  let reachableFiles = collectReachableSourceFiles(project);
  let root = commonDir(reachableFiles.map(file => file.fileName));
  let classes = extractClasses(project, reachableFiles);
  if (classes.length === 0) throw new Error(`No classes extending RpcTarget found in ${options.input}`);
  checkNameCollisions(classes);
  for (let klass of classes) {
    for (let method of klass.methods) {
      for (let param of method.params) checkSupported(param.type);
      checkSupported(method.returns);
    }
  }
  mkdirSync(outAbs, { recursive: true });
  return { classes, outAbs, runtimeImport, sourceFile, reachableFiles, root };
}

function checkNameCollisions(classes: ClassSpec[]): void {
  let seen = new Map<string, ClassSpec>();
  for (let klass of classes) {
    let prior = seen.get(klass.name);
    if (prior) {
      throw new Error(`Multiple RpcTarget classes share the name '${klass.name}'. ` +
          `Sources: ${prior.sourcePath}, ${klass.sourcePath}. Give one of them an explicit name.`);
    }
    seen.set(klass.name, klass);
  }
}

function checkSupported(type: TypeSpec): void {
  switch (type.kind) {
    case "unsupported": throw new Error(`Unsupported RPC type: ${type.text}`);
    case "array": checkSupported(type.element); break;
    case "tuple": for (let element of type.elements) checkSupported(element); break;
    case "object": for (let prop of type.props) checkSupported(prop.type); break;
    case "record": checkSupported(type.value); break;
    case "union": for (let variant of type.variants) checkSupported(variant); break;
  }
}

function emitArtifacts(p: Prepared): void {
  writeFileSync(join(p.outAbs, "specs.ts"), emitSpecsModule(p.classes));
  log(p.outAbs, "specs.ts");
  writeFileSync(join(p.outAbs, "validators.ts"), emitValidatorsModule(p.runtimeImport));
  log(p.outAbs, "validators.ts");
  writeFileSync(join(p.outAbs, "clients.ts"), emitClientsModule(p.classes, p.runtimeImport));
  log(p.outAbs, "clients.ts");
}

function emitSpecsModule(classes: ClassSpec[]): string {
  return `// Generated by capnweb-typecheck gen. Do not edit.\n` +
    `export const validators = {\n` +
    classes.map(klass => `  ${JSON.stringify(klass.name)}: ${formatSpec(klass, 2)},`).join("\n") +
    `\n};\n`;
}

function emitValidatorsModule(runtimeImport: string): string {
  return `// Generated by capnweb-typecheck gen. Do not edit.\n` +
    `import { __capnweb_registerRpcValidators } from ${JSON.stringify(runtimeImport)};\n` +
    `import { validators } from "./specs.js";\n\n` +
    `export function registerCapnwebValidators(classes: Record<string, Function>): void {\n` +
    `  __capnweb_registerRpcValidators(classes, Object.values(validators));\n` +
    `}\n`;
}

function emitClientsModule(classes: ClassSpec[], runtimeImport: string): string {
  let parts = [
    `// Generated by capnweb-typecheck gen. Do not edit.`,
    `import { __capnweb_bindClientValidator } from ${JSON.stringify(runtimeImport)};`,
    `import { validators } from "./specs.js";`,
    ``,
  ];
  for (let klass of classes) {
    let key = JSON.stringify(klass.name);
    parts.push(`export function ${wrapFunctionName(klass.name)}<T>(stub: T): T {`);
    parts.push(`  return __capnweb_bindClientValidator(stub as object, validators[${key}]) as T;`);
    parts.push(`}`);
    parts.push(``);
    parts.push(`export function ${wrapSessionFunctionName(klass.name)}<T>(session: T): T {`);
    parts.push(`  let main = (session as { getRemoteMain(): object }).getRemoteMain();`);
    parts.push(`  __capnweb_bindClientValidator(main, validators[${key}]);`);
    parts.push(`  return session;`);
    parts.push(`}`);
    parts.push(``);
  }
  return parts.join("\n");
}

function emitWorkerEntry(
    importPath: string, hasDefault: boolean, classes: ClassSpec[],
    outAbs: string, root: string): string {
  let registration = emitRegistrationImportsAndCall(classes, outAbs,
      sourcePath => join(outAbs, "source", relative(root, sourcePath)));
  return `// Generated by capnweb-typecheck gen. Do not edit.\n` +
    `import { registerCapnwebValidators } from "./validators.js";\n` +
    `${registration.imports.join("\n")}\n` +
    `registerCapnwebValidators({ ${registration.entries.join(", ")} });\n` +
    `export * from ${JSON.stringify(importPath)};\n` +
    (hasDefault ? `export { default } from ${JSON.stringify(importPath)};\n` : "");
}

type RegistrationEmit = { imports: string[]; entries: string[] };

export function emitViteRegistration(
    classes: ClassRegistration[], inputAbs: string,
    validatorsAbs: string): { imports: string; call: string } {
  let registration = emitRegistrationImportsAndCall(classes, dirname(inputAbs),
      sourcePath => sourcePath, inputAbs);
  let imports = `import { registerCapnwebValidators as __capnweb_registerValidators } ` +
    `from ${JSON.stringify(jsImportPath(relative(dirname(inputAbs), validatorsAbs)))};\n` +
    `${registration.imports.join("\n")}`;
  let call = `__capnweb_registerValidators({ ${registration.entries.join(", ")} });`;
  return { imports, call };
}

function emitRegistrationImportsAndCall(
    classes: ClassRegistration[], baseDir: string,
    sourcePathFor: (sourcePath: string) => string,
    localSourcePath?: string): RegistrationEmit {
  let imports: string[] = [];
  let entries: string[] = [];
  let named = new Map<string, string[]>();
  let defaults: string[] = [];
  for (let klass of classes) {
    if (localSourcePath && klass.sourcePath === localSourcePath) {
      entries.push(`${JSON.stringify(klass.name)}: ${klass.isDefault ? klass.name : klass.valueName}`);
      continue;
    }
    let importPath = jsImportPath(relative(baseDir, sourcePathFor(klass.sourcePath)));
    let alias = `__capnweb_${klass.valueName}`;
    entries.push(`${JSON.stringify(klass.name)}: ${alias}`);
    if (klass.isDefault) defaults.push(`import ${alias} from ${JSON.stringify(importPath)};`);
    else {
      let group = named.get(importPath) ?? [];
      group.push(`${klass.name} as ${alias}`);
      named.set(importPath, group);
    }
  }
  for (let [importPath, group] of named) {
    imports.push(`import { ${group.join(", ")} } from ${JSON.stringify(importPath)};`);
  }
  imports.push(...defaults);
  return { imports, entries };
}

function makeGenResult(classes: ClassSpec[]): GenResult {
  return {
    classes: classes.map(c => c.name),
    registrations: classes.map(({ name, valueName, isDefault, sourcePath }) =>
        ({ name, valueName, isDefault, sourcePath })),
  };
}

const GEN_ONLY_KEYS = new Set(["valueName", "isDefault", "sourcePath"]);

function formatSpec(value: unknown, indent: number): string {
  let json = JSON.stringify(value, (key, v) => GEN_ONLY_KEYS.has(key) ? undefined : v, 2);
  return json.split("\n").map((line, i) => i === 0 ? line : " ".repeat(indent) + line).join("\n");
}

function jsImportPath(path: string): string {
  let normalized = path.split(/[/\\]+/).join("/");
  let ext = extname(normalized);
  if (ext) normalized = normalized.slice(0, -ext.length) + ".js";
  if (!normalized.startsWith("./") && !normalized.startsWith("../")) normalized = "./" + normalized;
  return normalized;
}

function log(outAbs: string, name: string): void {
  console.log(`Generated ${relative(process.cwd(), join(outAbs, name))}`);
}

export type { GenOptions, GenResult } from "./types.js";
